apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis  
        role: metadata  
        tier: backend
    spec:
      containers:
      - image: redis
        # imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379
          # protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: redis-config
          items:
          - key: redis-config
            path: redis.conf