apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomato-api
  namespace: tomato-api-ns
  labels:
    app: tomato-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomato-api
  template:
    metadata:
      labels:
        app: tomato-api
    spec:
      terminationGracePeriodSeconds: 31
      containers:
      - name: tomato-api
        image: asia.gcr.io/able-stock-380702/tomato-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8765
          name: web-port
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8765
        #     scheme: HTTP
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8765
        #     scheme: HTTP
      # volumes:
      #   - name: volumn-config
      #     configMap:
      #       name: api-config
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: api-config
                key: DATABASE_URL
          - name: FAST_HOST_URL
            valueFrom:
              configMapKeyRef:
                name: api-config
                key: FAST_HOST_URL
          - name: BUCKET
            valueFrom:
              configMapKeyRef:
                name: api-config
                key: BUCKET
          - name: GCS_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: api-config
                key: GCS_PROJECT_ID
          - name: GCS_BUCKET_1
            valueFrom:
              configMapKeyRef:
                name: api-config
                key: GCS_BUCKET_1
          - name: GOOGLE_APPLICATION_CREDENTIALS
            valueFrom:
              configMapKeyRef:
                name: api-config
                key: GOOGLE_APPLICATION_CREDENTIALS
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: api-config
                key: TZ


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: tomato-api
#   namespace: tomato-api-ns
#   labels:
#     app: tomato-api
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: tomato-api
#   template:
#     metadata:
#       labels:
#         app: tomato-api
#     spec:
#       terminationGracePeriodSeconds: 30
#       containers:
#       - name: tomato-api
#         image: asia.gcr.io/able-stock-380702/tomato-api:latest
#         # imagePullPolicy: Always
#         ports:
#         - containerPort: 8765
#           name: web-port
#           protocol: TCP
#       volumes:
#         - name: volumn-config
#           configMap:
#             name: api-config
#         # DATABASE_URL: DATABASE_URL
#         # HOST_URL: HOST_URL
#         # BUCKET: BUCKET
#         # GCS_PROJECT_ID: GCS_PROJECT_ID
#         # GCS_BUCKET_1: GCS_BUCKET_1
#         # GOOGLE_APPLICATION_CREDENTIALS: GOOGLE_APPLICATION_CREDENTIALS
#         # TZ: TZ

#         # livenessProbe:
#         #   httpGet:
#         #     path: /health
#         #     port: 8765
#         #     scheme: HTTP
#         # readinessProbe:
#         #   httpGet:
#         #     path: /health
#         #     port: 8765
#         #     scheme: HTTP


          
#       # imagePullSecrets:
#       # - name: registry-..